language: android
jdk: oraclejdk8
sudo: false

android:
 components:
 - tools
 - platform-tools
 - tools
 - build-tools-25.0.3
 - build-tools-26.0.2
 - android-23
 - android-19
 - sys-img-armeabi-v7a-android-19

before_script:
- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew test"

after_failure: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"/TeamCode/build/reports/tests/testDebugUnitTest
    git init
    git checkout -b gh-pages
    git remote add origin git@github.com:medude/ftc_app.git
    git pull origin gh-pages
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -q https://medude:$GITHUB_API_KEY@github.com/medude/ftc_app gh-pages &2>/dev/null
    cd "$TRAVIS_BUILD_DIR"
    echo Done
  fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ${TRAVIS_BUILD_DIR}/reports/tests/testDebugUnitTest
  on:
    branch: master
